@php
    $isClient = auth()->user()->hasRole('client');
    $referralLayout = $isClient ? 'layouts.client' : 'layouts.app';
    $referralSection = $isClient ? 'client_content' : 'content';
@endphp
@extends($referralLayout)

@section($referralSection)
<style>
    .referral-client-page .referral-card { background: rgba(7, 13, 36, 0.95); border: 1px solid rgba(59, 130, 246, 0.18); }
    .referral-client-page .referral-input { background: rgba(15, 23, 42, 0.82); border: 1px solid rgba(148, 163, 184, 0.22); color: #f8fafc; }
    .referral-client-page .referral-input:focus { border-color: #3b82f6; outline: none; }
</style>

<div class="{{ $isClient ? 'referral-client-page relative z-10 max-w-7xl mx-auto space-y-6' : 'max-w-7xl mx-auto px-4 py-8 space-y-8' }}">
    <div class="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
        <div><p class="text-xs font-bold uppercase tracking-wider {{ $isClient ? 'text-blue-400' : 'text-indigo-600' }}">Refer &amp; Earn</p><h1 class="mt-1 text-3xl font-extrabold {{ $isClient ? 'text-white' : 'text-slate-900' }}">Referral Dashboard</h1><p class="mt-2 {{ $isClient ? 'text-slate-400' : 'text-slate-500' }}">Track clients, commissions, and monthly payout requests.</p></div>
        <a href="{{ route('referral.enroll') }}" class="text-sm font-bold {{ $isClient ? 'text-blue-300 hover:text-white' : 'text-indigo-700' }}">Payout profile &amp; agreement</a>
    </div>
    <section class="referral-card rounded-lg p-5 {{ $isClient ? 'text-slate-200' : 'border border-indigo-200 bg-indigo-50' }}">
        <label class="block text-sm font-bold mb-2">Generate and share your referral link</label>
        <div class="flex flex-col gap-3 sm:flex-row">
            <input id="client-referral-link" readonly value="{{ url('/register/client?ref='.$profile->referral_code) }}" class="referral-input min-w-0 flex-1 rounded-lg px-3 py-2 text-sm" @if(!$isClient) style="background:#fff;border:1px solid #c7d2fe;color:#334155" @endif>
            <button type="button" data-copy-target="client-referral-link" class="copy-referral-link rounded-lg bg-blue-600 px-4 py-2 text-sm font-bold text-white hover:bg-blue-500"><i class="fa-regular fa-copy mr-2"></i>Copy link</button>
        </div>
        <p class="mt-2 text-xs {{ $isClient ? 'text-slate-400' : 'text-slate-600' }}">Referral code: <span class="font-mono font-bold">{{ $profile->referral_code }}</span>. This code remains stable so previously shared links keep working.</p>
    </section>
    @if(session('success'))<div class="rounded-lg border px-4 py-3 {{ $isClient ? 'border-emerald-500/30 bg-emerald-500/10 text-emerald-200' : 'border-emerald-200 bg-emerald-50 text-emerald-800' }}">{{ session('success') }}</div>@endif
    <div class="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
        @foreach([['Total clients',$totalClients],['Active clients',$activeClients],['Monthly revenue','₹'.number_format($monthlyRevenue,2)],['Available commission','₹'.number_format($available,2)]] as [$label,$value])
            <section class="referral-card rounded-lg p-5"><p class="text-sm {{ $isClient ? 'text-slate-400' : 'text-slate-500' }}">{{ $label }}</p><p class="mt-1 text-3xl font-bold {{ $isClient ? 'text-white' : 'text-slate-900' }}">{{ $value }}</p></section>
        @endforeach
    </div>
    <div class="flex flex-wrap gap-2 text-xs font-bold"><span class="rounded-full bg-emerald-500/10 px-3 py-1.5 text-emerald-400">{{ $activeClients }} Active</span><span class="rounded-full bg-slate-500/10 px-3 py-1.5 {{ $isClient ? 'text-slate-300' : 'text-slate-600' }}">{{ $closedClients }} Closed</span><span class="rounded-full bg-rose-500/10 px-3 py-1.5 text-rose-400">{{ $lostClients }} Lost</span><span class="rounded-full bg-amber-500/10 px-3 py-1.5 text-amber-400">₹{{ number_format($pending,2) }} Pending</span><span class="rounded-full bg-blue-500/10 px-3 py-1.5 text-blue-400">₹{{ number_format($paid,2) }} Paid</span></div>
    <section class="referral-card rounded-lg p-5 {{ $isClient ? 'text-slate-200' : '' }}"><h2 class="font-bold">How you earn</h2><p class="mt-2 text-sm {{ $isClient ? 'text-slate-400' : 'text-slate-500' }}">Share your link/code or submit a lead. Commission becomes available after Finance confirms the referred client's payment, excluding GST. There is no withdrawal threshold; approved payouts are processed monthly.</p></section>
    <div class="grid gap-6 lg:grid-cols-2">
        <section class="referral-card rounded-lg {{ $isClient ? 'text-slate-200' : 'border border-slate-200 bg-white' }}"><div class="border-b border-white/10 p-5"><h2 class="font-bold">Submit a client lead</h2></div><form method="POST" action="{{ route('referral.leads.store') }}" class="grid gap-3 p-5">@csrf<input required name="company_name" placeholder="Company name" class="referral-input rounded-lg px-3 py-2"><input required name="contact_name" placeholder="Contact name" class="referral-input rounded-lg px-3 py-2"><div class="grid grid-cols-2 gap-3"><input name="email" type="email" placeholder="Email" class="referral-input rounded-lg px-3 py-2"><input name="phone_number" placeholder="Phone" class="referral-input rounded-lg px-3 py-2"></div><input name="service_required" placeholder="Service required" class="referral-input rounded-lg px-3 py-2"><textarea name="notes" placeholder="Notes" class="referral-input rounded-lg px-3 py-2"></textarea><button class="justify-self-start rounded-lg bg-blue-600 px-4 py-2 font-bold text-white hover:bg-blue-500">Submit for review</button></form></section>
        <section class="referral-card rounded-lg {{ $isClient ? 'text-slate-200' : 'border border-slate-200 bg-white' }}"><div class="border-b border-white/10 p-5"><h2 class="font-bold">Withdrawal request</h2><p class="text-sm {{ $isClient ? 'text-slate-400' : 'text-slate-500' }}">No minimum threshold. Finance processes approved requests monthly.</p></div><form method="POST" action="{{ route('referral.withdrawals.store') }}" class="flex gap-3 p-5">@csrf<input required type="number" min="1" step="0.01" name="amount" max="{{ $available }}" placeholder="Amount" class="referral-input min-w-0 flex-1 rounded-lg px-3 py-2"><button class="rounded-lg bg-slate-800 px-4 py-2 font-bold text-white hover:bg-slate-700">Request</button></form><div class="border-t border-white/10 px-5 pb-4">@forelse($withdrawals->take(5) as $request)<div class="flex items-center justify-between border-b border-white/5 py-2 text-sm"><span>₹{{ number_format($request->amount,2) }}</span><span class="font-semibold capitalize {{ $request->status === 'paid' ? 'text-emerald-400' : ($request->status === 'rejected' ? 'text-rose-400' : 'text-amber-400') }}">{{ $request->status }}</span></div>@empty<p class="py-3 text-sm {{ $isClient ? 'text-slate-400' : 'text-slate-500' }}">No payout requests yet.</p>@endforelse</div></section>
    </div>
    <section class="referral-card overflow-x-auto rounded-lg {{ $isClient ? 'text-slate-200' : 'border border-slate-200 bg-white' }}"><div class="border-b border-white/10 p-5"><h2 class="font-bold">Invoice tracker</h2><p class="mt-1 text-sm {{ $isClient ? 'text-slate-400' : 'text-slate-500' }}">Month-wise Finance-verified billing, excluding GST.</p></div><table class="min-w-full text-sm"><thead class="{{ $isClient ? 'bg-white/5 text-slate-400' : 'bg-slate-50 text-slate-600' }} text-left"><tr><th class="p-3">Month</th><th class="p-3">Invoices</th><th class="p-3">Billing</th><th class="p-3">Commission earned</th></tr></thead><tbody>@forelse($invoiceTracker as $month)<tr class="border-t border-white/10"><td class="p-3 font-semibold">{{ \Illuminate\Support\Carbon::createFromFormat('Y-m', $month->month_key)->format('F Y') }}</td><td class="p-3">{{ $month->invoice_count }}</td><td class="p-3">₹{{ number_format($month->billing_amount,2) }}</td><td class="p-3 font-semibold text-emerald-400">₹{{ number_format($month->commission_amount,2) }}</td></tr>@empty<tr><td colspan="4" class="p-6 {{ $isClient ? 'text-slate-400' : 'text-slate-500' }}">No verified billing entries yet.</td></tr>@endforelse</tbody></table></section>
    <section class="referral-card overflow-x-auto rounded-lg {{ $isClient ? 'text-slate-200' : 'border border-slate-200 bg-white' }}"><div class="border-b border-white/10 p-5"><h2 class="font-bold">Commission ledger</h2><p class="mt-1 text-sm {{ $isClient ? 'text-slate-400' : 'text-slate-500' }}">Earned, pending, and paid commission activity.</p></div><table class="min-w-full text-sm"><thead class="{{ $isClient ? 'bg-white/5 text-slate-400' : 'bg-slate-50 text-slate-600' }} text-left"><tr><th class="p-3">Date</th><th class="p-3">Client</th><th class="p-3">Revenue</th><th class="p-3">Commission</th><th class="p-3">Rule</th><th class="p-3">Status</th></tr></thead><tbody>@forelse($ledger as $entry)<tr class="border-t border-white/10"><td class="p-3">{{ $entry->earned_at->format('d M Y') }}</td><td class="p-3">{{ $entry->clientReferral?->client?->clientProfile?->company_name ?? $entry->clientReferral?->client?->name }}</td><td class="p-3">₹{{ number_format($entry->revenue_amount,2) }}</td><td class="p-3 font-semibold">₹{{ number_format($entry->commission_amount,2) }}</td><td class="p-3">{{ str_contains($entry->commission_type_snapshot, 'percentage') ? number_format($entry->commission_value_snapshot,2).'%' : '₹'.number_format($entry->commission_value_snapshot,2) }}</td><td class="p-3 font-semibold capitalize">{{ $entry->status === 'available' ? 'Earned' : $entry->status }}</td></tr>@empty<tr><td colspan="6" class="p-6 {{ $isClient ? 'text-slate-400' : 'text-slate-500' }}">No commission entries yet.</td></tr>@endforelse</tbody></table><div class="p-4">{{ $ledger->links() }}</div></section>
    <div class="grid gap-6 lg:grid-cols-2">
        <section class="referral-card overflow-x-auto rounded-lg {{ $isClient ? 'text-slate-200' : 'border border-slate-200 bg-white' }}"><div class="border-b border-white/10 p-5"><h2 class="font-bold">Referred clients</h2></div><table class="min-w-full text-sm"><thead class="{{ $isClient ? 'bg-white/5 text-slate-400' : 'bg-slate-50 text-slate-600' }} text-left"><tr><th class="p-3">Client</th><th class="p-3">Commission rule</th><th class="p-3">Status</th></tr></thead><tbody>@forelse($referrals as $referral)<tr class="border-t border-white/10"><td class="p-3">{{ $referral->client?->clientProfile?->company_name ?? $referral->client?->name }}<br><span class="{{ $isClient ? 'text-slate-400' : 'text-slate-500' }}">{{ $referral->client?->email }}</span></td><td class="p-3">@if($referral->rule){{ str_contains($referral->rule->commission_type, 'percentage') ? number_format($referral->rule->commission_value,2).'%' : '₹'.number_format($referral->rule->commission_value,2) }}@else Not set @endif</td><td class="p-3 font-semibold capitalize">{{ $referral->status }}</td></tr>@empty<tr><td colspan="3" class="p-5 {{ $isClient ? 'text-slate-400' : 'text-slate-500' }}">No referred clients yet.</td></tr>@endforelse</tbody></table></section>
        <section class="referral-card overflow-x-auto rounded-lg {{ $isClient ? 'text-slate-200' : 'border border-slate-200 bg-white' }}"><div class="border-b border-white/10 p-5"><h2 class="font-bold">Submitted leads</h2></div><table class="min-w-full text-sm"><tbody>@forelse($leads as $lead)<tr class="border-t border-white/10"><td class="p-3">{{ $lead->company_name }}<br><span class="{{ $isClient ? 'text-slate-400' : 'text-slate-500' }}">{{ $lead->contact_name }}</span></td><td class="p-3 capitalize">{{ $lead->status }}</td></tr>@empty<tr><td colspan="2" class="p-5 {{ $isClient ? 'text-slate-400' : 'text-slate-500' }}">No leads submitted yet.</td></tr>@endforelse</tbody></table></section>
    </div>
</div>
<script>
document.addEventListener('DOMContentLoaded', function () {
    document.querySelectorAll('.copy-referral-link').forEach(function (button) {
        button.addEventListener('click', async function () {
            const input = document.getElementById(button.dataset.copyTarget);
            await navigator.clipboard.writeText(input.value);
            const original = button.innerHTML;
            button.innerHTML = '<i class="fa-solid fa-check mr-2"></i>Link copied';
            window.setTimeout(function () { button.innerHTML = original; }, 1800);
        });
    });
});
</script>
@endsection
