<x-app-layout>
<div class="min-h-screen bg-slate-950 -mt-6 -mx-4 sm:-mx-6 lg:-mx-8 p-6 text-slate-100"><div class="max-w-[1600px] mx-auto">
<div class="mb-6"><h1 class="text-3xl font-black">Advanced Analytics & Reports</h1><p class="text-slate-400 mt-1">Operational conversion, partner, client, manager portfolio, and GST-excluded revenue metrics.</p></div>
<div class="grid md:grid-cols-3 gap-3 mb-6">@foreach([['Submission → Interview',$conversion['submission_interview'],$conversion['submitted'].' submissions'],['Interview → Joining',$conversion['interview_joining'],$conversion['interviewed'].' interviews'],['Submission → Joining',$conversion['submission_joining'],$conversion['joined'].' joinings']] as $item)<div class="border border-slate-800 bg-slate-900 rounded-lg p-5"><div class="text-sm text-slate-400">{{ $item[0] }}</div><div class="text-3xl font-black mt-2">{{ $item[1] }}%</div><div class="mt-3 h-2 bg-slate-800 rounded overflow-hidden"><div class="h-full bg-cyan-500" style="width:{{ min(100,$item[1]) }}%"></div></div><div class="text-xs text-slate-500 mt-2">{{ $item[2] }}</div></div>@endforeach</div>
<div class="grid xl:grid-cols-2 gap-5 mb-5">
@php $tables=[['Vendor Performance Score',$vendors,['Vendor','Submit','Interview','Selected','Joined','Score']],['Sales Team Performance (Manager Portfolios)',$managers,['Manager','Clients','Submit','Joined','Revenue']]]; @endphp
@foreach($tables as [$title,$rows,$heads])<section class="border border-slate-800 bg-slate-900/70 rounded-lg overflow-hidden"><h2 class="font-bold text-lg p-4 border-b border-slate-800">{{ $title }}</h2><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="text-xs uppercase text-slate-500"><tr>@foreach($heads as $head)<th class="p-3 text-left">{{ $head }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-800">@forelse($rows->take(15) as $row)<tr>@if(isset($row['vendor']))<td class="p-3 font-bold">{{ $row['vendor']->name }}</td><td class="p-3">{{ $row['submissions'] }}</td><td class="p-3">{{ $row['interviews'] }}</td><td class="p-3">{{ $row['selections'] }}</td><td class="p-3">{{ $row['joinings'] }}</td><td class="p-3 text-cyan-300 font-bold">{{ $row['score'] }}/100</td>@else<td class="p-3 font-bold">{{ $row['manager']->name }}</td><td class="p-3">{{ $row['clients'] }}</td><td class="p-3">{{ $row['submissions'] }}</td><td class="p-3">{{ $row['joinings'] }}</td><td class="p-3">₹{{ number_format($row['revenue']) }}</td>@endif</tr>@empty<tr><td colspan="6" class="p-8 text-center text-slate-500">No data yet.</td></tr>@endforelse</tbody></table></div></section>@endforeach
</div>
<div class="grid xl:grid-cols-2 gap-5 mb-5"><section class="border border-slate-800 bg-slate-900/70 rounded-lg overflow-hidden"><h2 class="font-bold text-lg p-4 border-b border-slate-800">Client Hiring Speed</h2><table class="w-full text-sm"><thead class="text-xs uppercase text-slate-500"><tr><th class="p-3 text-left">Client</th><th>Industry</th><th>Hires</th><th>Avg days</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($clientSpeed->take(15) as $row)<tr><td class="p-3 font-bold">{{ $row['client']->name }}</td><td class="text-center">{{ $row['industry'] }}</td><td class="text-center">{{ $row['hires'] }}</td><td class="text-center text-cyan-300 font-bold">{{ $row['days'] }}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-slate-500">No joined placements yet.</td></tr>@endforelse</tbody></table></section>
<section class="border border-slate-800 bg-slate-900/70 rounded-lg overflow-hidden"><h2 class="font-bold text-lg p-4 border-b border-slate-800">Industry-wise Paid Revenue</h2><table class="w-full text-sm"><thead class="text-xs uppercase text-slate-500"><tr><th class="p-3 text-left">Industry</th><th>Placements</th><th>Revenue</th></tr></thead><tbody class="divide-y divide-slate-800">@forelse($industryRevenue as $row)<tr><td class="p-3 font-bold">{{ $row['industry'] }}</td><td class="text-center">{{ $row['placements'] }}</td><td class="text-right p-3">₹{{ number_format($row['revenue']) }}</td></tr>@empty<tr><td colspan="3" class="p-8 text-center text-slate-500">No paid revenue yet.</td></tr>@endforelse</tbody></table></section></div>
<section class="border border-slate-800 bg-slate-900/70 rounded-lg p-5"><h2 class="font-bold text-lg">Monthly Growth (Last 12 Months)</h2><div class="flex gap-4 text-xs mt-2 text-slate-400"><span class="text-blue-400">Submissions</span><span class="text-violet-400">Interviews</span><span class="text-emerald-400">Joinings</span></div>@php $peak=max(1,$months->max(fn($m)=>max($m['submissions'],$m['interviews'],$m['joinings']))); @endphp<div class="mt-5 h-56 flex items-end gap-2 border-b border-slate-700">@foreach($months as $month)<div class="flex-1 h-full flex items-end justify-center gap-px" title="{{ $month['label'] }}: {{ $month['submissions'] }} submissions, {{ $month['interviews'] }} interviews, {{ $month['joinings'] }} joinings, ₹{{ number_format($month['revenue']) }} revenue"><div class="w-2 bg-blue-500" style="height:{{ max(2,$month['submissions']/$peak*100) }}%"></div><div class="w-2 bg-violet-500" style="height:{{ max(2,$month['interviews']/$peak*100) }}%"></div><div class="w-2 bg-emerald-500" style="height:{{ max(2,$month['joinings']/$peak*100) }}%"></div></div>@endforeach</div><div class="flex gap-2 mt-2">@foreach($months as $month)<div class="flex-1 text-center text-[10px] text-slate-500">{{ $month['label'] }}</div>@endforeach</div><div class="mt-4 grid grid-cols-2 md:grid-cols-4 gap-2">@foreach($months->take(-4) as $month)<div class="bg-slate-950 p-3 rounded"><div class="text-xs text-slate-500">{{ $month['label'] }} paid revenue</div><div class="font-bold">₹{{ number_format($month['revenue']) }}</div></div>@endforeach</div></section>
</div></div>
</x-app-layout>
