<x-app-layout>
<div class="min-h-screen bg-slate-950 -mt-6 -mx-4 sm:-mx-6 lg:-mx-8 px-4 sm:px-6 lg:px-8 py-8 text-slate-100">
<div class="revenue-tabs-stack max-w-7xl mx-auto space-y-7">
    <div><p class="text-xs font-bold uppercase text-emerald-400">Finance Operations</p><h1 class="mt-1 text-3xl font-extrabold">Revenue &amp; Payout Control</h1><p class="mt-1 text-sm text-slate-400">Client billing, GST, vendor/referral payouts, deductions, and incentive calculation.</p></div>
    <nav class="flex gap-2 overflow-x-auto rounded-2xl border border-white/10 bg-slate-950/90 p-2 shadow-xl" aria-label="Revenue sections">@foreach([['overview','Overview & Manual Entry','fa-gauge-high'],['billing','Client Billing','fa-file-invoice-dollar'],['vendors','Vendor Payouts','fa-handshake'],['referrals','Referral Commission','fa-share-nodes'],['deductions','Deductions','fa-receipt']] as [$tab,$label,$icon])<button type="button" data-revenue-tab="{{ $tab }}" class="shrink-0 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-bold text-slate-300"><i class="fa-solid {{ $icon }} mr-2"></i>{{ $label }}</button>@endforeach</nav>

    <div data-revenue-panel="overview" class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach([['Base billing','₹'.number_format($baseBilling,2),'text-blue-300'],['GST calculated','₹'.number_format($gstTotal,2),'text-amber-300'],['Billing incl. GST','₹'.number_format($billingWithGst,2),'text-emerald-300'],['Outstanding','₹'.number_format($outstanding,2),'text-rose-300']] as [$label,$value,$color])
            <section class="rounded-lg border border-white/10 bg-slate-900 p-5"><p class="text-sm text-slate-400">{{ $label }}</p><p class="mt-2 text-2xl font-extrabold {{ $color }}">{{ $value }}</p></section>
        @endforeach
    </div>

    <section data-revenue-panel="overview" class="rounded-2xl border border-emerald-500/20 bg-slate-900 p-5"><div class="flex items-center justify-between gap-4"><div><h2 class="font-bold">Manual Revenue Entry</h2><p class="text-sm text-slate-400">Record exceptional revenue outside placement invoices. Every entry stores its operator and reason.</p></div></div>
        <form method="POST" action="{{ route('admin.marketplace.revenue.store') }}" class="manual-revenue-form mt-4 grid gap-3 md:grid-cols-5">@csrf<select name="client_id" class="rounded bg-slate-800 border-white/10"><option value="">General revenue</option>@foreach($revenueClients as $client)<option value="{{ $client->id }}">{{ $client->name }}</option>@endforeach</select><input required name="amount" type="number" min="0.01" step="0.01" placeholder="Amount" class="rounded bg-slate-800 border-white/10"><input required name="recognized_on" type="date" value="{{ now()->toDateString() }}" class="rounded bg-slate-800 border-white/10"><input name="reference" maxlength="100" placeholder="Reference" class="rounded bg-slate-800 border-white/10"><input required name="reason" maxlength="1000" placeholder="Reason" class="rounded bg-slate-800 border-white/10"><button class="md:col-span-5 rounded bg-emerald-700 py-2 font-bold">Record Revenue</button></form>
        @if($manualRevenueEntries->isNotEmpty())<details class="mt-4"><summary class="cursor-pointer text-sm text-emerald-300">Recent manual entries ({{ $manualRevenueEntries->count() }})</summary><div class="mt-2 divide-y divide-white/10">@foreach($manualRevenueEntries as $entry)<div class="flex justify-between gap-4 py-2 text-sm"><span>{{ $entry->client?->name ?? 'General' }} · {{ $entry->reason }}<small class="block text-slate-500">{{ $entry->creator?->name }} · {{ $entry->reference }}</small></span><b>₹{{ number_format($entry->amount,2) }} · {{ $entry->recognized_on->format('d M Y') }}</b></div>@endforeach</div></details>@endif
    </section>

    <section data-revenue-panel="billing" hidden class="rounded-2xl border border-white/10 bg-slate-900 overflow-hidden"><div class="p-5 border-b border-white/10"><h2 class="font-bold">Client-wise billing tracking</h2><p class="text-sm text-slate-400">Commercial calculation supports percentage and flat rules. GST is added only when enabled for that client.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-white/5 text-left text-slate-400"><tr><th class="p-3">Client / Placement</th><th class="p-3">Base</th><th class="p-3">GST</th><th class="p-3">Invoice total</th><th class="p-3">Status</th><th class="p-3">Invoice</th></tr></thead><tbody>@forelse($billingPage as $row)<tr class="border-t border-white/10"><td class="p-3"><b>{{ $row['client_name'] }}</b><br><span class="text-slate-400">{{ $row['candidate_name'] }} · {{ $row['job_title'] }}</span></td><td class="p-3">₹{{ number_format((float)($row['invoice_amount'] ?? 0),2) }}</td><td class="p-3">₹{{ number_format((float)($row['gst_amount'] ?? 0),2) }} <span class="text-xs text-slate-500">({{ number_format((float)($row['gst_rate'] ?? 0),0) }}%)</span></td><td class="p-3 font-bold text-emerald-300">₹{{ number_format((float)($row['invoice_total'] ?? 0),2) }}</td><td class="p-3">{{ $row['status'] }}</td><td class="p-3">@if($row['invoice_amount'])<a href="{{ route('admin.billing.invoice.pdf',$row['application']) }}" class="inline-flex items-center gap-2 rounded bg-blue-600 px-3 py-2 text-xs font-bold text-white"><i class="fa-solid fa-file-pdf"></i>PDF</a>@else<span class="text-slate-500">Not configured</span>@endif</td></tr>@empty<tr><td colspan="6" class="p-6 text-slate-400">No billable placements.</td></tr>@endforelse</tbody></table></div><div class="border-t border-white/10 p-4">{{ $billingPage->appends(["finance_tab"=>"billing"])->links() }}</div></section>

    <div data-revenue-panel="vendors" hidden class="grid gap-6 xl:grid-cols-2">
        <section class="rounded-lg border border-white/10 bg-slate-900 overflow-hidden"><div class="p-5 border-b border-white/10"><h2 class="font-bold">Vendor-wise commission tracking</h2><p class="text-sm text-slate-400">Gross fixed payouts minus applied replacement deductions.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-white/5 text-left text-slate-400"><tr><th class="p-3">Vendor</th><th class="p-3">Joinings</th><th class="p-3">Gross</th><th class="p-3">Deductions</th><th class="p-3">Net</th></tr></thead><tbody>@forelse($vendorSummary as $row)<tr class="border-t border-white/10"><td class="p-3 font-semibold">{{ $row['partner']->name }}</td><td class="p-3">{{ $row['placements'] }}</td><td class="p-3">₹{{ number_format($row['gross'],2) }}</td><td class="p-3 text-rose-300">₹{{ number_format($row['applied'],2) }}@if($row['pending'])<br><span class="text-xs text-amber-300">₹{{ number_format($row['pending'],2) }} pending</span>@endif</td><td class="p-3 font-bold text-emerald-300">₹{{ number_format($row['net'],2) }}</td></tr>@empty<tr><td colspan="5" class="p-6 text-slate-400">No eligible vendor payouts.</td></tr>@endforelse</tbody></table></div></section>

        <section class="rounded-lg border border-white/10 bg-slate-900 p-5"><h2 class="font-bold">Sales incentive calculator</h2><p class="mt-1 text-sm text-slate-400">Calculate an incentive without posting it to any ledger.</p><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="text-sm">Revenue<input id="sales-revenue" type="number" min="0" step="0.01" value="0" class="mt-1 w-full rounded bg-slate-800 border-white/10"></label><label class="text-sm">Model<select id="sales-model" class="mt-1 w-full rounded bg-slate-800 border-white/10"><option value="percentage">Percentage</option><option value="flat">Flat amount</option></select></label><label class="text-sm">Rate / amount<input id="sales-rate" type="number" min="0" step="0.01" value="10" class="mt-1 w-full rounded bg-slate-800 border-white/10"></label><div class="rounded-lg border border-emerald-500/20 bg-emerald-500/10 p-4"><p class="text-xs text-emerald-300">Calculated incentive</p><p id="sales-result" class="mt-1 text-2xl font-extrabold text-white">₹0.00</p></div></div></section>
    </div>

    <section data-revenue-panel="referrals" hidden class="rounded-2xl border border-white/10 bg-slate-900 overflow-hidden"><div class="p-5 border-b border-white/10"><h2 class="font-bold">Referral commission (% / flat)</h2><p class="text-sm text-slate-400">Finance-verified referral calculations using the client-specific rule snapshot.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-white/5 text-left text-slate-400"><tr><th class="p-3">Partner</th><th class="p-3">Client</th><th class="p-3">Revenue</th><th class="p-3">Rule</th><th class="p-3">Commission</th><th class="p-3">Status</th></tr></thead><tbody>@forelse($referralLedger as $entry)<tr class="border-t border-white/10"><td class="p-3">{{ $entry->referralPartner?->name }}</td><td class="p-3">{{ $entry->clientReferral?->client?->name }}</td><td class="p-3">₹{{ number_format($entry->revenue_amount,2) }}</td><td class="p-3">{{ str_contains($entry->commission_type_snapshot,'percentage') ? number_format($entry->commission_value_snapshot,2).'%' : '₹'.number_format($entry->commission_value_snapshot,2) }}</td><td class="p-3 font-bold text-emerald-300">₹{{ number_format($entry->commission_amount,2) }}</td><td class="p-3 capitalize">{{ $entry->status === 'available' ? 'earned' : $entry->status }}</td></tr>@empty<tr><td colspan="6" class="p-6 text-slate-400">No referral commissions.</td></tr>@endforelse</tbody></table></div></section>

    <section data-revenue-panel="deductions" hidden class="rounded-2xl border border-white/10 bg-slate-900 overflow-hidden"><div class="p-5 border-b border-white/10"><h2 class="font-bold">Replacement penalty deductions</h2><p class="text-sm text-slate-400">Existing credit notes applied against vendor payouts.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-white/5 text-left text-slate-400"><tr><th class="p-3">Vendor</th><th class="p-3">Amount</th><th class="p-3">Reason</th><th class="p-3">Status</th></tr></thead><tbody>@forelse($creditNotes as $note)<tr class="border-t border-white/10"><td class="p-3">{{ $note->partner?->name }}</td><td class="p-3 text-rose-300">₹{{ number_format($note->amount,2) }}</td><td class="p-3">{{ $note->reason }}</td><td class="p-3 capitalize">{{ $note->status }}</td></tr>@empty<tr><td colspan="4" class="p-6 text-slate-400">No replacement deductions.</td></tr>@endforelse</tbody></table></div></section>
</div></div>
<style>.manual-revenue-form input,.manual-revenue-form select{color-scheme:dark}.revenue-tabs-stack>[data-revenue-panel]+[data-revenue-panel]{margin-top:1.5rem}[data-revenue-panel][hidden]{display:none!important}</style>
<script>document.addEventListener('DOMContentLoaded',()=>{const revenue=document.getElementById('sales-revenue'),model=document.getElementById('sales-model'),rate=document.getElementById('sales-rate'),result=document.getElementById('sales-result');const calculate=()=>{const r=Math.max(0,Number(revenue?.value)||0),v=Math.max(0,Number(rate?.value)||0),amount=model?.value==='percentage'?r*v/100:v;if(result)result.textContent=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(amount)};[revenue,model,rate].filter(Boolean).forEach(el=>el.addEventListener('input',calculate));calculate();const tabs=[...document.querySelectorAll('[data-revenue-tab]')],panels=[...document.querySelectorAll('[data-revenue-panel]')];const show=name=>{panels.forEach(p=>p.hidden=p.dataset.revenuePanel!==name);tabs.forEach(b=>{const active=b.dataset.revenueTab===name;b.classList.toggle('bg-emerald-500/20',active);b.classList.toggle('border-emerald-400/40',active);b.classList.toggle('text-emerald-200',active)});history.replaceState(null,'','?finance_tab='+name+(name==='billing'&&new URLSearchParams(location.search).get('billing_page')?'&billing_page='+new URLSearchParams(location.search).get('billing_page'):''))};tabs.forEach(b=>b.addEventListener('click',()=>show(b.dataset.revenueTab)));const requested=new URLSearchParams(location.search).get('finance_tab');show(tabs.some(b=>b.dataset.revenueTab===requested)?requested:'overview')});</script>
</x-app-layout>
