<x-app-layout>
<div class="min-h-screen bg-slate-950 -mt-6 -mx-4 sm:-mx-6 lg:-mx-8 px-4 sm:px-6 lg:px-8 py-8 text-slate-100"><div class="risk-stack max-w-7xl mx-auto space-y-10">
    <header><p class="text-xs font-bold uppercase text-rose-400">Marketplace Protection</p><h1 class="mt-1 text-3xl font-extrabold">Risk &amp; Fraud Control</h1><p class="mt-1 text-sm text-slate-300">Duplicate identity/resume signals, restricted vendors, suspicious shared IPs, and traceable activity.</p></header>
    <nav class="flex gap-2 overflow-x-auto rounded-2xl border border-white/10 bg-slate-950/90 p-2 shadow-xl backdrop-blur-xl" aria-label="Risk sections">@foreach([['overview','Overview','fa-gauge-high'],['review','Review Queue','fa-user-check'],['resumes','Resume Matches','fa-file-circle-exclamation'],['entities','Clients & Vendors','fa-building-shield'],['identities','Identity Alerts','fa-fingerprint'],['ips','IP Logs','fa-network-wired']] as [$tab,$label,$icon])<button type="button" data-risk-tab="{{ $tab }}" class="shrink-0 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-bold text-slate-300"><i class="fa-solid {{ $icon }} mr-2"></i>{{ $label }}</button>@endforeach</nav>
    <div id="overview" data-risk-panel="overview" class="grid grid-cols-2 gap-3 lg:grid-cols-4">@foreach([['Duplicate resume groups',$duplicateResumes->count(),'text-amber-300','fa-file-circle-exclamation','resumes'],['Duplicate client identities',$duplicateClients->count(),'text-rose-300','fa-address-card','entities'],['Restricted vendors',$restrictedVendors->count(),'text-rose-300','fa-user-slash','entities'],['Shared admin IPs',$sharedIps->count(),'text-blue-300','fa-network-wired','ips']] as [$label,$value,$color,$icon,$tab])<button type="button" data-risk-open="{{ $tab }}" class="text-left rounded-2xl border border-white/10 bg-slate-900/80 p-3.5 shadow-lg hover:border-cyan-400/30"><div class="flex items-center gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white/10 border border-white/10 {{ $color }}"><i class="fa-solid {{ $icon }} text-base"></i></span><div class="min-w-0"><p class="truncate text-[11px] font-bold uppercase tracking-wide text-slate-300">{{ $label }}</p><p class="text-2xl font-extrabold leading-none mt-1 {{ $color }}">{{ $value }}</p></div><i class="fa-solid fa-arrow-right ml-auto text-xs text-slate-500"></i></div></button>@endforeach</div>

    @if(session('success'))<div class="rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-4 text-emerald-200">{{ session('success') }}</div>@endif
    <section data-risk-panel="review" hidden id="review-queue" class="scroll-mt-24 rounded-2xl border border-white/10 bg-slate-900 overflow-hidden"><div class="p-5 border-b border-white/10"><h2 class="font-bold">Duplicate enforcement queue</h2><p class="text-sm text-slate-400">Pending candidates cannot be submitted to jobs. Genuine releases the candidate; Duplicate keeps them blocked; Fraud also restricts the vendor.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-white/5 text-left text-slate-400"><tr><th class="p-3">Candidate</th><th class="p-3">Vendor</th><th class="p-3">Matched record</th><th class="p-3">Signals</th><th class="p-3">Decision</th></tr></thead><tbody>@forelse($pendingCandidateReviews as $candidate)<tr class="border-t border-white/10"><td class="p-3"><b>{{ trim($candidate->first_name.' '.$candidate->last_name) }}</b><br><span class="text-slate-400">{{ $candidate->email }} · {{ $candidate->phone_number }}</span></td><td class="p-3">{{ $candidate->partner?->name }}</td><td class="p-3">#{{ $candidate->duplicate_of_candidate_id }}<br><span class="text-slate-400">{{ $candidate->duplicateOf?->partner?->name }}</span></td><td class="p-3">{{ collect($candidate->duplicate_reasons)->join(', ') }} @if($candidate->duplicate_blocked_job_id)<br><span class="text-amber-300 text-xs">Blocked on: {{ optional(\App\Models\Job::find($candidate->duplicate_blocked_job_id))->title ?? ('job #'.$candidate->duplicate_blocked_job_id) }} — Genuine will submit it</span>@endif</td><td class="p-3"><form method="POST" action="{{ route('admin.risk-control.candidates.review',$candidate) }}" class="flex min-w-[360px] gap-2">@csrf<select name="decision" class="rounded bg-slate-800 border-white/10 text-white"><option value="genuine">Genuine — release &amp; submit</option><option value="duplicate">Duplicate — block</option><option value="fraud">Fraud — block &amp; restrict vendor</option></select><input name="review_notes" placeholder="Review notes" class="min-w-0 flex-1 rounded bg-slate-800 border-white/10 text-white"><button class="rounded bg-blue-600 px-3 font-bold text-white">Apply</button></form></td></tr>@empty<tr><td colspan="5" class="p-6 text-slate-400">No candidates awaiting duplicate review.</td></tr>@endforelse</tbody></table></div></section>

    <section data-risk-panel="resumes" hidden id="resume-matches" class="scroll-mt-24 rounded-2xl border border-white/10 bg-slate-900 overflow-hidden"><div class="p-5 border-b border-white/10"><h2 class="font-bold">Duplicate resume detection</h2><p class="text-sm text-slate-400">Exact SHA-256 file matches across direct and vendor candidates. Refreshed hourly.</p></div><div class="p-5 space-y-3">@forelse($duplicateResumes as $group)<div class="rounded-lg border border-amber-500/20 bg-amber-500/5 p-4"><div class="font-mono text-xs text-amber-300">{{ substr($group->first()['fingerprint'],0,20) }}… · {{ $group->count() }} matches</div><div class="mt-2 flex flex-wrap gap-2">@foreach($group as $record)<span class="rounded bg-white/5 px-3 py-1.5 text-xs">{{ $record['name'] }} · {{ $record['owner'] }} · {{ $record['source'] }}</span>@endforeach</div></div>@empty<p class="text-sm text-slate-400">No exact duplicate resume files detected.</p>@endforelse</div></section>

    <div data-risk-panel="entities" hidden id="clients-vendors" class="grid gap-8 xl:grid-cols-2 scroll-mt-24">
        <section class="rounded-lg border border-white/10 bg-slate-900 overflow-hidden"><div class="p-5 border-b border-white/10"><h2 class="font-bold">Duplicate client detection</h2><p class="text-sm text-slate-400">Matching phone, GST, or PAN across client profiles.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-white/5 text-left text-slate-400"><tr><th class="p-3">Signal</th><th class="p-3">Value</th><th class="p-3">Clients</th></tr></thead><tbody>@forelse($duplicateClients as $match)<tr class="border-t border-white/10"><td class="p-3">{{ $match['type'] }}</td><td class="p-3 font-mono text-xs">{{ $match['value'] }}</td><td class="p-3">{{ $match['profiles']->pluck('user.name')->filter()->join(', ') }}</td></tr>@empty<tr><td colspan="3" class="p-6 text-slate-400">No duplicate client identities detected.</td></tr>@endforelse</tbody></table></div></section>
        <section class="rounded-lg border border-white/10 bg-slate-900 overflow-hidden"><div class="p-5 border-b border-white/10"><h2 class="font-bold">Vendor blacklist</h2><p class="text-sm text-slate-400">Restricted status is the enforced blacklist state.</p></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><tbody>@forelse($restrictedVendors as $vendor)<tr class="border-t border-white/10"><td class="p-3"><b>{{ $vendor->name }}</b><br><span class="text-slate-400">{{ $vendor->email }}</span></td><td class="p-3 text-rose-300">Restricted</td><td class="p-3"><a href="{{ route('admin.partners.show',$vendor) }}" class="text-blue-300 hover:text-white">Review</a></td></tr>@empty<tr><td class="p-6 text-slate-400">No restricted vendors.</td></tr>@endforelse</tbody></table></div></section>
    </div>

    <section data-risk-panel="identities" hidden id="identity-alerts" class="scroll-mt-24 rounded-2xl border border-white/10 bg-slate-900 overflow-hidden"><div class="p-5 border-b border-white/10"><h2 class="font-bold">Suspicious identity alerts</h2><p class="text-sm text-slate-400">Repeated candidate email/phone identities, especially across multiple vendors.</p></div><div class="grid gap-5 p-5 lg:grid-cols-2"><div><h3 class="mb-2 text-sm font-bold text-slate-300">Duplicate emails</h3>@forelse($duplicateCandidateEmails as $signal)<div class="flex justify-between border-b border-white/10 py-2 text-sm"><span>{{ $signal->identity_value }}</span><span class="{{ $signal->partner_count > 1 ? 'text-rose-300' : 'text-amber-300' }}">{{ $signal->total }} records / {{ $signal->partner_count }} vendors</span></div>@empty<p class="text-sm text-slate-400">No duplicate emails.</p>@endforelse</div><div><h3 class="mb-2 text-sm font-bold text-slate-300">Duplicate phones</h3>@forelse($duplicateCandidatePhones as $signal)<div class="flex justify-between border-b border-white/10 py-2 text-sm"><span>{{ $signal->identity_value }}</span><span class="{{ $signal->partner_count > 1 ? 'text-rose-300' : 'text-amber-300' }}">{{ $signal->total }} records / {{ $signal->partner_count }} vendors</span></div>@empty<p class="text-sm text-slate-400">No duplicate phones.</p>@endforelse</div></div></section>

    <section data-risk-panel="ips" hidden id="ip-logs" class="scroll-mt-24 rounded-2xl border border-white/10 bg-slate-900 overflow-hidden"><div class="p-5 border-b border-white/10 flex items-center justify-between"><div><h2 class="font-bold">IP tracking log</h2><p class="text-sm text-slate-400">New activity events retain IP and browser/device information.</p></div><a href="{{ route('admin.activity-logs.index') }}" class="text-sm font-bold text-blue-300">Full activity log</a></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-white/5 text-left text-slate-400"><tr><th class="p-3">Time</th><th class="p-3">IP</th><th class="p-3">Actor</th><th class="p-3">Event</th><th class="p-3">Device</th></tr></thead><tbody>@forelse($recentIpLogs as $log)<tr class="border-t border-white/10"><td class="p-3">{{ $log->occurred_at?->format('d M, h:i A') }}</td><td class="p-3 font-mono text-xs">{{ $log->ip_address }}</td><td class="p-3">{{ $log->actor_name ?? 'System' }}</td><td class="p-3">{{ $log->title }}</td><td class="p-3 max-w-72 truncate text-xs text-slate-400" title="{{ $log->user_agent }}">{{ $log->user_agent }}</td></tr>@empty<tr><td colspan="5" class="p-6 text-slate-400">IP capture begins with new activity events after this release.</td></tr>@endforelse</tbody></table></div></section>
</div></div>
<script>
document.addEventListener('DOMContentLoaded',()=>{const tabs=[...document.querySelectorAll('[data-risk-tab]')],panels=[...document.querySelectorAll('[data-risk-panel]')];const show=name=>{panels.forEach(p=>p.hidden=p.dataset.riskPanel!==name);tabs.forEach(b=>{const active=b.dataset.riskTab===name;b.classList.toggle('bg-cyan-500/20',active);b.classList.toggle('border-cyan-400/40',active);b.classList.toggle('text-cyan-200',active)});history.replaceState(null,'','#risk-'+name)};tabs.forEach(b=>b.addEventListener('click',()=>show(b.dataset.riskTab)));document.querySelectorAll('[data-risk-open]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.riskOpen)));const requested=location.hash.replace('#risk-','');show(tabs.some(b=>b.dataset.riskTab===requested)?requested:'overview')});
</script>
<style>.risk-stack > * + *{margin-top:2rem}.risk-stack > nav + #overview{margin-top:1rem}.risk-stack > #overview + #review-queue{margin-top:2rem}</style>
</x-app-layout>
