<x-app-layout>
<div class="min-h-screen -mt-6 px-4 sm:px-6 lg:px-8 py-10 relative overflow-hidden">
    <div class="absolute -top-20 -left-20 w-96 h-96 bg-amber-500 rounded-full blur-[145px] opacity-20 animate-pulse pointer-events-none"></div>
    <div class="relative z-10 max-w-7xl mx-auto">
        <header class="flex flex-col md:flex-row md:items-end md:justify-between gap-4 border-b border-white/10 pb-6 mb-7">
            <div><a href="{{ route('admin.dashboard') }}" class="inline-flex items-center text-cyan-300 hover:text-white text-xs font-bold uppercase tracking-wider mb-2"><i class="fa-solid fa-arrow-left mr-2"></i>Dashboard</a><h1 class="text-4xl font-extrabold text-white">Finance Offer Queue</h1><p class="text-blue-200 mt-1">Review client-submitted offers and release verified billing data.</p></div>
            <div class="inline-flex items-center gap-2 self-start md:self-auto px-4 py-2 rounded-full bg-amber-500/10 border border-amber-400/30 text-amber-200"><b>{{ $offers->total() }}</b><span class="text-xs uppercase font-bold">Awaiting review</span></div>
        </header>
        @if(session('success'))<div class="mb-5 px-5 py-3 bg-emerald-500/15 border border-emerald-400/40 text-emerald-200 rounded-xl font-bold"><i class="fa-solid fa-circle-check mr-2"></i>{{ session('success') }}</div>@endif
        <section class="bg-slate-900/65 backdrop-blur-xl border border-white/15 rounded-3xl overflow-hidden shadow-2xl">
            <div class="px-6 py-4 border-b border-white/10"><h2 class="font-extrabold text-white">Offer Updates</h2><p class="text-xs text-slate-400 mt-0.5">Invoice values exclude GST</p></div>
            <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-blue-950/60 text-cyan-300 uppercase text-xs tracking-wider"><tr><th class="px-6 py-4 text-left">Candidate</th><th class="px-6 py-4 text-left">Client / Job</th><th class="px-6 py-4 text-left">CTC</th><th class="px-6 py-4 text-left">Invoice excl. GST</th><th class="px-6 py-4 text-right">Action</th></tr></thead><tbody class="divide-y divide-white/10">@forelse($offers as $offer)<tr class="group hover:bg-white/5"><td class="px-6 py-5"><div class="flex items-center gap-3"><span class="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center font-black text-white">{{ strtoupper(substr($offer->candidate_name ?: 'C',0,1)) }}</span><div><b class="text-white">{{ $offer->candidate_name }}</b><small class="block text-slate-500">Application #{{ $offer->id }}</small></div></div></td><td class="px-6 py-5"><b class="text-blue-100">{{ $offer->job?->user?->name }}</b><small class="block text-slate-400">{{ $offer->job?->title }}</small></td><td class="px-6 py-5"><span class="inline-flex px-3 py-1 rounded-full bg-violet-500/10 border border-violet-400/30 text-violet-200 font-bold">₹{{ number_format($offer->final_ctc,2) }}</span></td><td class="px-6 py-5 font-extrabold text-emerald-300">₹{{ number_format($offer->invoice_amount,2) }}</td><td class="px-6 py-5 text-right"><form method="POST" action="{{ route('admin.finance-offers.approve',$offer) }}">@csrf<button class="rounded-lg bg-emerald-600 hover:bg-emerald-500 px-4 py-2 text-white font-bold shadow-lg shadow-emerald-950/30"><i class="fa-solid fa-check mr-2"></i>Review Complete</button></form></td></tr>@empty<tr><td colspan="5" class="px-6 py-16"><div class="max-w-sm mx-auto text-center"><span class="w-16 h-16 mx-auto rounded-2xl bg-emerald-500/10 border border-emerald-400/20 flex items-center justify-center text-emerald-300 text-2xl"><i class="fa-solid fa-circle-check"></i></span><h3 class="text-white font-extrabold mt-4">Queue is clear</h3><p class="text-slate-400 mt-1">No offers are waiting for Finance review.</p></div></td></tr>@endforelse</tbody></table></div>
            @if($offers->hasPages())<div class="p-5 border-t border-white/10">{{ $offers->links() }}</div>@endif
        </section>
    </div>
</div>
</x-app-layout>
