<!doctype html>
<html><head><meta charset="utf-8"><style>
body{font-family:DejaVu Sans,sans-serif;color:#172033;font-size:12px;margin:34px}.header{border-bottom:3px solid #2563eb;padding-bottom:18px;margin-bottom:24px}.brand{font-size:25px;font-weight:700}.muted{color:#64748b}.right{text-align:right}.grid{width:100%;border-collapse:collapse}.grid td{vertical-align:top}.box{border:1px solid #cbd5e1;padding:14px;margin:18px 0}.items{width:100%;border-collapse:collapse;margin-top:24px}.items th{background:#eff6ff;text-align:left;padding:10px;border-bottom:1px solid #bfdbfe}.items td{padding:11px 10px;border-bottom:1px solid #e2e8f0}.totals{width:46%;margin-left:auto;margin-top:18px;border-collapse:collapse}.totals td{padding:7px}.grand{font-size:16px;font-weight:700;border-top:2px solid #2563eb}.footer{margin-top:50px;border-top:1px solid #e2e8f0;padding-top:12px;color:#64748b;font-size:10px}
</style></head><body>
<div class="header"><table class="grid"><tr><td><div class="brand">SimplyHiree</div><div class="muted">Recruitment Services Invoice</div></td><td class="right"><b>INVOICE</b><br>SH-INV-{{ str_pad((string)$application->id,6,'0',STR_PAD_LEFT) }}<br><span class="muted">{{ optional($application->invoice_generated_at ?? now())->format('d M Y') }}</span></td></tr></table></div>
<table class="grid"><tr><td width="55%"><b>Bill To</b><div class="box">{{ $application->job?->user?->clientProfile?->company_name ?? $application->job?->user?->name }}<br>{{ $application->job?->user?->email }}<br>{{ $application->job?->user?->clientProfile?->address }}<br>@if($application->job?->user?->clientProfile?->gst_number)GSTIN: {{ $application->job->user->clientProfile->gst_number }}@endif</div></td><td width="5%"></td><td><b>Placement</b><div class="box">Candidate: {{ $invoice['candidate_name'] }}<br>Role: {{ $invoice['job_title'] }}<br>Joining: {{ $invoice['joining_date']?->format('d M Y') }}<br>Final CTC: ₹{{ number_format((float)$invoice['final_ctc'],2) }}</div></td></tr></table>
<table class="items"><thead><tr><th>Description</th><th class="right">Amount</th></tr></thead><tbody><tr><td>Recruitment service fee — {{ str_replace('_',' ',(string)$invoice['billing_type']) }}</td><td class="right">₹{{ number_format((float)$invoice['invoice_amount'],2) }}</td></tr></tbody></table>
<table class="totals"><tr><td>Subtotal</td><td class="right">₹{{ number_format((float)$invoice['invoice_amount'],2) }}</td></tr><tr><td>GST ({{ number_format((float)$invoice['gst_rate'],0) }}%)</td><td class="right">₹{{ number_format((float)$invoice['gst_amount'],2) }}</td></tr><tr class="grand"><td>Total</td><td class="right">₹{{ number_format((float)$invoice['invoice_total'],2) }}</td></tr></table>
<div class="footer">Generated automatically by SimplyHiree. Payment status: {{ $invoice['status'] }}. This document uses the commercial terms locked to this placement.</div>
</body></html>
