@once
<style>
    .response-card{position:relative;overflow:hidden;border:1px solid rgba(2,6,23,.92);border-radius:1.5rem;background:linear-gradient(115deg,rgba(8,47,73,.74),rgba(7,17,42,.95) 62%);box-shadow:0 18px 42px rgba(2,8,29,.28);transition:transform .22s ease,box-shadow .22s ease}
    .response-card::before{content:"";position:absolute;inset:0 auto 0 0;width:4px;background:linear-gradient(#22d3ee,#2563eb)}
    .response-card:hover{transform:translateY(-2px);box-shadow:0 22px 46px rgba(2,8,29,.34)}
    .response-card:nth-child(4n+2){background:linear-gradient(115deg,rgba(67,20,78,.58),rgba(7,17,42,.95) 62%)}.response-card:nth-child(4n+2)::before{background:linear-gradient(#e879f9,#7c3aed)}
    .response-card:nth-child(4n+3){background:linear-gradient(115deg,rgba(88,45,5,.52),rgba(7,17,42,.95) 62%)}.response-card:nth-child(4n+3)::before{background:linear-gradient(#fbbf24,#f97316)}
    .response-card:nth-child(4n+4){background:linear-gradient(115deg,rgba(6,78,59,.54),rgba(7,17,42,.95) 62%)}.response-card:nth-child(4n+4)::before{background:linear-gradient(#34d399,#0ea5e9)}
    .response-card-grid{display:grid;gap:1.5rem}.response-fact{display:grid;grid-template-columns:5.6rem minmax(0,1fr);gap:.75rem;padding:.48rem 0;border-bottom:1px solid rgba(255,255,255,.07)}.response-fact:last-child{border-bottom:0}.response-fact b{color:#67e8f9;font-size:.65rem;letter-spacing:.06em;text-transform:uppercase}.response-fact span{color:#e2e8f0;font-size:.82rem;line-height:1.35}.response-actions{display:flex;flex-wrap:wrap;align-items:center;gap:.55rem;margin-top:1.25rem;padding-top:1rem;border-top:1px solid rgba(255,255,255,.09)}.response-action{transition:transform .18s ease,filter .18s ease,box-shadow .18s ease}.response-action:hover{transform:translateY(-2px);filter:brightness(1.08);box-shadow:0 10px 20px rgba(2,8,23,.28)}
    @media(min-width:1024px){.response-card-grid{grid-template-columns:minmax(15rem,1.05fr) minmax(20rem,1.45fr) 12rem;align-items:start}}
</style>
@endonce
@php
    $candidate=$app->candidate;$candidateUser=$app->candidateUser;$profile=$candidateUser?->profile;
    $name=$candidate?trim(($candidate->first_name??'').' '.($candidate->last_name??'')):($candidateUser?->name??'Candidate');$name=$name?:'Candidate';$initial=strtoupper(substr($name,0,1));
    $email=$candidate?->email??$candidateUser?->email??'Email not available';$phone=$candidate?->phone_number??$profile?->phone_number;$resume=$candidate?->resume_path??$profile?->resume_path;
    $reviewStatus=$app->hiring_status;$isRejected=$reviewStatus==='Client Rejected';$isMaybe=$reviewStatus==='Maybe';$isAwaitingReview=in_array($reviewStatus,[null,''],true);$isShortlisted=in_array($reviewStatus,['Shortlisted','shortlisted'],true);$isSelected=$reviewStatus==='Selected';$isInterviewed=$reviewStatus==='Interviewed';
    $joiningStatus=$app->joined_status;$isJoined=$joiningStatus==='Joined';$didNotJoin=$joiningStatus==='Did Not Join';$hasLeft=$joiningStatus==='Left';$joined=!empty($joiningStatus);
    $statusLabel=$app->joined_status?:($isRejected?'Rejected':($isMaybe?'Maybe':($isShortlisted?'Shortlisted':($isAwaitingReview?'Screened by Admin':$reviewStatus))));
    $statusStyle=$isRejected?'border-rose-300/35 bg-rose-500/18 text-rose-100':($isMaybe?'border-amber-300/35 bg-amber-500/18 text-amber-100':($isShortlisted?'border-emerald-300/35 bg-emerald-500/18 text-emerald-100':'border-cyan-300/35 bg-cyan-500/18 text-cyan-100'));
    $skills=$candidate?->skills??$profile?->skills;$experience=$candidate?->experience_status??$profile?->experience_status;$education=$candidate?->education_level??$profile?->qualification_degree;$ctc=$candidate?->expected_ctc??$profile?->expected_ctc;$location=$candidate?->preferred_location??$candidate?->location??$profile?->location;$currentRole=$candidate?->current_designation??$profile?->current_role;$notice=$candidate?->notice_period??$profile?->notice_period;
    $latestRound=$app->interviewRounds->sortBy('round_number')->last();$latestRoundStatus=$latestRound?->status;
    $canSchedule=$isShortlisted||in_array($reviewStatus,['Interview Scheduled','Interviewed','No-Show'],true);
    $canSelect=!$joined&&!$isSelected&&($isShortlisted||$isInterviewed||in_array($reviewStatus,['Interview Scheduled','No-Show'],true)||$latestRound);
    $isDetailView=$isDetailView??false;$contactHref=$phone?'tel:'.preg_replace('/[^0-9+]/','',$phone):'mailto:'.$email;
@endphp
<article class="response-card p-5 pl-6 md:p-6 md:pl-7">
    <div class="response-card-grid">
        <div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h2 class="text-xl font-black text-white">{{ $name }}</h2>@if($isAwaitingReview&&!$joined)<span class="rounded-full border border-amber-300/30 bg-amber-400/15 px-2 py-0.5 text-[9px] font-extrabold uppercase text-amber-100">Ready to review</span>@endif<span class="rounded-full border px-2.5 py-1 text-[10px] font-extrabold uppercase {{ $statusStyle }}">{{ $statusLabel }}</span></div><p class="mt-2 truncate text-sm text-blue-200">{{ $email }}</p><div class="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-300">@if($phone)<span><i class="fa-solid fa-phone mr-1.5 text-cyan-300"></i>{{ $phone }}</span>@endif<span><i class="fa-regular fa-clock mr-1.5 text-cyan-300"></i>Applied {{ $app->created_at?->format('d M Y') }}</span></div><div class="mt-4 flex flex-wrap gap-2 text-[11px] font-bold text-slate-200">@if($experience)<span class="rounded-md border border-white/10 bg-white/5 px-2 py-1"><i class="fa-solid fa-briefcase mr-1 text-cyan-300"></i>{{ $experience }}</span>@endif @if($ctc)<span class="rounded-md border border-white/10 bg-white/5 px-2 py-1"><i class="fa-solid fa-indian-rupee-sign mr-1 text-cyan-300"></i>{{ $ctc }}</span>@endif @if($location)<span class="rounded-md border border-white/10 bg-white/5 px-2 py-1"><i class="fa-solid fa-location-dot mr-1 text-cyan-300"></i>{{ $location }}</span>@endif</div></div>
        <div class="rounded-2xl border border-white/10 bg-slate-950/25 px-4 py-3"><div class="response-fact"><b>Current</b><span>{{ $currentRole?:'Not specified' }}</span></div><div class="response-fact"><b>Education</b><span>{{ $education?:'Not specified' }}</span></div><div class="response-fact"><b>Skills</b><span class="line-clamp-2">{{ $skills?:'Not specified' }}</span></div><div class="response-fact"><b>Availability</b><span>{{ $notice?:'Not specified' }}</span></div></div>
        <div class="flex min-h-40 flex-col items-center justify-center rounded-2xl border border-white/10 bg-white/[.06] p-4 text-center"><div class="flex h-14 w-14 items-center justify-center rounded-full border border-cyan-200/25 bg-cyan-400/10 text-xl font-black text-cyan-100">{{ $initial }}</div><p class="mt-3 text-xs font-bold text-slate-100">{{ $resume?'CV attached':'Profile available' }}</p><a href="{{ $contactHref }}" class="response-action mt-3 inline-flex items-center gap-2 rounded-xl border border-cyan-300/30 bg-cyan-500/10 px-3 py-2 text-xs font-extrabold text-cyan-100"><i class="fa-solid fa-phone"></i>Contact</a></div>
    </div>
    @if($app->assessmentBadge())
        <div class="mt-4 inline-flex flex-wrap items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2">
            <span class="text-[11px] font-bold uppercase tracking-wide text-slate-400"><i class="fa-solid fa-clipboard-check mr-1 text-violet-300"></i>Assessment</span>
            @include('applications._assessment_cell', ['app' => $app, 'showRoute' => 'client.assessment-results.show'])
        </div>
    @endif
    <div class="response-actions">
        @if($isDetailView)
            <span class="inline-flex items-center gap-2 rounded-xl border border-cyan-200/35 bg-cyan-500/15 px-3 py-2.5 text-xs font-extrabold text-cyan-50" title="The complete candidate profile is open"><i class="fa-solid fa-circle-check"></i>Profile open</span>
        @else
            <a href="{{ route('client.applications.show',$app) }}" class="response-action inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-3 py-2.5 text-xs font-extrabold text-white"><i class="fa-regular fa-user"></i>Profile</a>
        @endif
        @if($resume)<a href="{{ asset('storage/'.$resume) }}" target="_blank" class="response-action inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-indigo-500 to-violet-600 px-3 py-2.5 text-xs font-extrabold text-white"><i class="fa-regular fa-file-lines"></i>CV</a>@endif
        @if(!$joined&&!$isSelected)
            @if($isShortlisted)<form method="POST" action="{{ route('client.applications.undo-review',$app) }}">@csrf<button class="response-action rounded-xl bg-emerald-600 px-3 py-2.5 text-xs font-extrabold text-white"><i class="fa-solid fa-check mr-1"></i>Shortlisted <i class="fa-solid fa-rotate-left ml-1 text-[9px]"></i></button></form>@else<form method="POST" action="{{ route('client.applications.shortlist',$app) }}">@csrf<button class="response-action rounded-xl bg-gradient-to-r from-emerald-500 to-teal-600 px-3 py-2.5 text-xs font-extrabold text-white"><i class="fa-solid fa-check mr-1"></i>Shortlist</button></form>@endif
            @if($isMaybe)<form method="POST" action="{{ route('client.applications.undo-review',$app) }}">@csrf<button class="response-action rounded-xl bg-amber-500 px-3 py-2.5 text-xs font-extrabold text-slate-950"><i class="fa-regular fa-bookmark mr-1"></i>Maybe <i class="fa-solid fa-rotate-left ml-1 text-[9px]"></i></button></form>@else<form method="POST" action="{{ route('client.applications.maybe',$app) }}">@csrf<button class="response-action rounded-xl bg-gradient-to-r from-amber-400 to-orange-500 px-3 py-2.5 text-xs font-extrabold text-slate-950"><i class="fa-regular fa-bookmark mr-1"></i>Maybe</button></form>@endif
            @if($isRejected)<form method="POST" action="{{ route('client.applications.undo-review',$app) }}">@csrf<button class="response-action rounded-xl bg-rose-600 px-3 py-2.5 text-xs font-extrabold text-white"><i class="fa-solid fa-xmark mr-1"></i>Rejected <i class="fa-solid fa-rotate-left ml-1 text-[9px]"></i></button></form>@else<form method="POST" action="{{ route('client.applications.reject',$app) }}">@csrf<button class="response-action rounded-xl bg-gradient-to-r from-rose-500 to-pink-600 px-3 py-2.5 text-xs font-extrabold text-white"><i class="fa-solid fa-xmark mr-1"></i>Reject</button></form>@endif
        @endif
        @if($canSchedule&&!$joined&&!$isSelected)<a href="{{ route('client.applications.rounds.create',$app) }}" class="response-action inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-indigo-500 to-violet-600 px-3 py-2.5 text-xs font-extrabold text-white"><i class="fa-regular fa-calendar-plus"></i>{{ $latestRound?'Schedule next round':'Schedule interview' }}</a>@endif
        @if($latestRound&&$latestRoundStatus==='Scheduled'&&!$joined&&!$isSelected)
            <form method="POST" action="{{ route('client.rounds.appeared',$latestRound) }}">@csrf<button class="response-action rounded-xl bg-gradient-to-r from-sky-500 to-cyan-600 px-3 py-2.5 text-xs font-extrabold text-white"><i class="fa-solid fa-user-check mr-1"></i>Mark appeared</button></form>
            <form method="POST" action="{{ route('client.rounds.noshow',$latestRound) }}">@csrf<button class="response-action rounded-xl border border-orange-300/35 bg-orange-500/20 px-3 py-2.5 text-xs font-extrabold text-orange-50"><i class="fa-solid fa-user-slash mr-1"></i>Mark no-show</button></form>
        @elseif($latestRound&&$latestRoundStatus==='Appeared'&&!$joined&&!$isSelected)
            <a href="{{ route('client.rounds.feedback.create',$latestRound) }}" class="response-action inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-blue-500 to-indigo-600 px-3 py-2.5 text-xs font-extrabold text-white"><i class="fa-regular fa-clipboard"></i>Add feedback</a>
        @elseif(!$latestRound&&$reviewStatus==='Interview Scheduled'&&!$joined&&!$isSelected)
            <form method="POST" action="{{ route('client.applications.interview.appeared',$app) }}">@csrf<button class="response-action rounded-xl bg-gradient-to-r from-sky-500 to-cyan-600 px-3 py-2.5 text-xs font-extrabold text-white"><i class="fa-solid fa-user-check mr-1"></i>Mark appeared</button></form>
            <form method="POST" action="{{ route('client.applications.interview.noshow',$app) }}">@csrf<button class="response-action rounded-xl border border-orange-300/35 bg-orange-500/20 px-3 py-2.5 text-xs font-extrabold text-orange-50"><i class="fa-solid fa-user-slash mr-1"></i>Mark no-show</button></form>
        @endif
        @if($canSelect)<a href="{{ route('client.applications.select.show',$app) }}" class="response-action inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-fuchsia-500 to-purple-600 px-3 py-2.5 text-xs font-extrabold text-white"><i class="fa-solid fa-user-check"></i>Select Candidate</a>@elseif($isSelected&&!$joined)<a href="{{ route('client.applications.select.edit',$app) }}" class="response-action inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-fuchsia-500 to-purple-600 px-3 py-2.5 text-xs font-extrabold text-white"><i class="fa-solid fa-pen"></i>Edit offer</a><form method="POST" action="{{ route('client.applications.undo-review',$app) }}">@csrf<button class="response-action rounded-xl border border-white/20 bg-white/10 px-3 py-2.5 text-xs font-extrabold text-white"><i class="fa-solid fa-rotate-left mr-1"></i>Undo selection</button></form>@endif

        @if($isSelected&&!$joined)
            <form method="POST" action="{{ route('client.applications.markJoined',$app) }}">@csrf<button class="response-action rounded-xl border border-emerald-300 px-3 py-2.5 text-xs font-extrabold text-white shadow-lg" style="background:linear-gradient(135deg,#16a34a,#047857);color:#fff;box-shadow:0 8px 20px rgba(5,150,105,.28)"><i class="fa-solid fa-user-check mr-1 text-white"></i>Mark Joined</button></form>
            <form method="POST" action="{{ route('client.applications.markNotJoined',$app) }}">@csrf<button class="response-action rounded-xl border border-orange-300/40 bg-orange-500/20 px-3 py-2.5 text-xs font-extrabold text-orange-50"><i class="fa-solid fa-user-xmark mr-1"></i>Did Not Join</button></form>
        @elseif($isJoined)
            <a href="{{ route('client.applications.showLeftForm',$app) }}" class="response-action inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-orange-500 to-rose-600 px-3 py-2.5 text-xs font-extrabold text-white"><i class="fa-solid fa-person-walking-arrow-right"></i>Mark Left</a>
        @elseif($didNotJoin)
            <span class="inline-flex items-center gap-2 rounded-xl border border-orange-300/35 bg-orange-500/15 px-3 py-2.5 text-xs font-extrabold text-orange-100"><i class="fa-solid fa-circle-info"></i>Joining closed: Did Not Join</span>
        @elseif($hasLeft)
            <span class="inline-flex items-center gap-2 rounded-xl border border-rose-300/35 bg-rose-500/15 px-3 py-2.5 text-xs font-extrabold text-rose-100"><i class="fa-solid fa-circle-info"></i>Employment closed: Left</span>
        @endif
    </div>
    @if($latestRound)<div class="mt-5 border-t border-white/10 pt-4 text-xs text-blue-200"><i class="fa-solid fa-calendar-check mr-2 text-cyan-300"></i>Latest interview: Round {{ $latestRound->round_number }} - {{ $latestRound->status }} @if($latestRound->scheduled_at)on {{ $latestRound->scheduled_at->format('d M, g:i A') }}@endif</div>@endif
</article>
