<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\{ComplianceDocument,Job,JobApplication,ManualRevenueEntry,MarketplaceSetting,User};
use App\Services\AiSensyWhatsAppService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\{DB,Mail,Storage};
class AdminControlController extends Controller {
 public function legal(){return view('admin.control_panels.legal',['documents'=>ComplianceDocument::with(['party','uploader'])->latest()->paginate(25),'offers'=>JobApplication::with(['job.user','candidate','candidateUser'])->whereNotNull('offer_letter_path')->latest('offer_updated_at')->limit(50)->get(),'referrals'=>\App\Models\ReferralPartnerProfile::with('user')->latest()->limit(50)->get()]);}
 public function uploadDocument(Request $r){$d=$r->validate(['party_type'=>'required|in:vendor,client,global','party_id'=>'nullable|required_unless:party_type,global|exists:users,id','document_type'=>'required|in:vendor_agreement,client_agreement,nda,policy','title'=>'required|string|max:255','version'=>'nullable|string|max:30','file'=>'required|file|mimes:pdf,doc,docx|max:10240']);ComplianceDocument::create($d+['file_path'=>$r->file('file')->store('compliance','public'),'uploaded_by'=>auth()->id()]);return back()->with('success','Compliance document uploaded.');}
 public function marketing(){return view('admin.control_panels.marketing',['vendors'=>User::role('partner')->whereNull('parent_partner_id')->where('status','active')->count(),'clients'=>User::role('client')->where('status','active')->where('marketing_consent',true)->count(),'recent'=>DB::table('notifications')->latest('created_at')->limit(25)->get()]);}
 public function sendClients(Request $r, AiSensyWhatsAppService $wa){$d=$r->validate(['subject'=>'required|string|max:200','body'=>'required|string|max:5000','channels'=>'required|array|min:1','channels.*'=>'in:email,whatsapp,app']);$clients=User::role('client')->where('status','active')->where('marketing_consent',true)->with('profile')->get();$sent=0;foreach($clients as $client){try{if(in_array('app',$d['channels'],true))DB::table('notifications')->insert(['id'=>(string)\Illuminate\Support\Str::uuid(),'type'=>'App\\Notifications\\AdminBroadcastNotification','notifiable_type'=>User::class,'notifiable_id'=>$client->id,'data'=>json_encode(['title'=>$d['subject'],'message'=>$d['body'],'url'=>route('client.dashboard')]),'created_at'=>now(),'updated_at'=>now()]);if(in_array('email',$d['channels'],true))Mail::raw($d['body'],fn($m)=>$m->to($client->email,$client->name)->subject('[SimplyHiree] '.$d['subject']));if(in_array('whatsapp',$d['channels'],true)&&$client->profile?->phone_number)$wa->sendEventAlert($client->profile->phone_number,'client_broadcast',$d['subject'],$d['body']);$sent++;}catch(\Throwable $e){report($e);}}return back()->with('success',"Client broadcast processed for {$sent} clients.");}
 public function marketplace(){return view('admin.control_panels.marketplace',['settings'=>collect(['resume_visible_to_client'=>true,'screening_mandatory'=>true,'replacement_period_days'=>90,'commission_default_percent'=>10,'payment_release_days'=>30,'contract_staffing_service_fee'=>8])->mapWithKeys(fn($v,$k)=>[$k=>MarketplaceSetting::valueOf($k,$v)])]);}
 public function saveSettings(Request $r){$d=$r->validate(['resume_visible_to_client'=>'required|boolean','screening_mandatory'=>'required|boolean','replacement_period_days'=>'required|integer|min:0|max:730','commission_default_percent'=>'required|numeric|min:0|max:100','payment_release_days'=>'required|integer|min:0|max:365','contract_staffing_service_fee'=>'required|numeric|min:0|max:100']);foreach($d as $k=>$v)MarketplaceSetting::updateOrCreate(['key'=>$k],['value'=>(string)$v,'type'=>in_array($k,['resume_visible_to_client','screening_mandatory'])?'boolean':(is_int($v)?'integer':'decimal'),'updated_by'=>auth()->id()]);return back()->with('success','Marketplace defaults saved.');}
 public function forceClose(Request $r,Job $job){$r->validate(['reason'=>'required|string|max:1000']);$job->update(['status'=>'closed']);$this->audit('marketplace.force_close',$job,$r->reason);return back()->with('success','Job force closed.');}
 public function overrideCommission(Request $r,Job $job){$d=$r->validate(['payout_amount'=>'required|numeric|min:0','reason'=>'required|string|max:1000']);$job->update(['payout_amount'=>$d['payout_amount']]);$this->audit('marketplace.override_commission',$job,$d['reason']);return back()->with('success','Job commission overridden.');}
 public function clientAction(Request $r,User $client){$d=$r->validate(['action'=>'required|in:freeze,unfreeze,change_type','client_type'=>'nullable|required_if:action,change_type|string|max:100','reason'=>'required|string|max:1000']);if($d['action']==='freeze')$client->update(['status'=>'restricted']);elseif($d['action']==='unfreeze')$client->update(['status'=>'active']);else $client->clientProfile?->update(['service_required'=>$d['client_type']]);$this->audit('marketplace.client_'.$d['action'],$client,$d['reason']);return back()->with('success','Client control action completed.');}
 public function manualRevenue(Request $r){$d=$r->validate(['client_id'=>'nullable|exists:users,id','amount'=>'required|numeric|min:0.01','recognized_on'=>'required|date','reference'=>'nullable|string|max:100','reason'=>'required|string|max:1000']);ManualRevenueEntry::create($d+['created_by'=>auth()->id()]);return back()->with('success','Manual revenue entry recorded.');}
 private function audit(string $event,$subject,string $reason):void{app(\App\Services\SuperadminActivityService::class)->logEvent($event,(string)str($event)->headline(),$reason,'shield-halved',$subject);}
}
